language: python
python:
  - "3.6"      # current detault Python on Travis CI
# command to install dependencies
install:
  - conda install psi4 python=3.6 -c psi4
  - pip install numpy scipy
# command to run tests
script:
  - pytest
